### ISSUE TITLE
Atualização

### ISSUE THREAD

**Issue by andreadcsousa** [neylsoncrepalde/deflatebr#6]
Olá, Neylson! Tudo bem?

Na empresa em que trabalho, utilizam o pacote DeflateBR na linguagem R e funciona super bem, mas começamos a transcrever os códigos no Databricks e não conseguimos puxar o pacote em R para lá. Seria possível atualizar essa biblioteca em Python?

Ajudaria demais!

**Comment by andreadcsousa** [comment]
Resolvi fuçar o script, pois realmente preciso utilizar o pacote, e vi que ele ainda atualiza. Sendo desnecessária atualização ou modificação, no momento.

**Comment by neylsoncrepalde** [comment]
Ei @andreadcsousa. Vi seu issue aqui um pouco atrasado mas fico super feliz que conseguiram usar a biblioteca direitinho. Qualquer coisa, só nos chamar aqui. Abração!
